changelog:
  categories:
    - title: Enhancement
      labels:
        - Enhancement
    - title: bug fix
      labels:
        - -bug
        - fixs
  exclude:
    labels:
      - dependencies
    authors:
      - dependabot