name: conditions
on: push
jobs:
  skip-or-run:
    runs-on: ubuntu-latest
    steps:
      # - run: exit 1  # 終了ステータスが0以外のため、失敗扱い
      - uses: actions/checkout@v4
      - run: echo "workflow is fail"
        if: ${{ failure() }} # 失敗時に出力