name: methods
on: push
jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          CONSTANT_FUNC: ${{ contains('Hello', 'ell') }}
          START_WITH_FUNC: ${{ startsWith('Hello', 'He') }}
          END_WITH_FUNC: ${{ endsWith('Hello', 'llo') }}
