name: Manual
on: 
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: Hello
        description: a cheerful word
        required: true
jobs:
  paramtest:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}"
      # このコマンドで実行 gh workflow run param.yml -f greeting=hello