name: variable
on: push
env:
  EXAMPLE: workflow sample text
jobs:
  variable:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ vars.USERNAME }}
      - uses: actions/checkout@v4
  env:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${EXAMPLE}"
      - uses: actions/checkout@v4

  